name: S3 Deployment

on: push
permissions:
   contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing NPM packages
        run: npm ci

      - name: Building project
        run: npm run build

      - name: Running tests
        run: npm run test

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v4.4.3
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: production-files
          path: ./build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 sync ./build s3://$AWS_BUCKET_NAME --region $AWS_REGION --delete
